---
# file: playbook-expand-swap.yml

- name: expand swap partition
  hosts: all
  become: yes
  vars:
    vg_name: sysvg
    lv_name: swap
    min_size_gb: 4

  tasks:

    - name: "does {{ vg_name }}/{{ lv_name }} exist?"
      assert:
        that:
          - ansible_lvm.vgs.{{ vg_name }} is defined
          - ansible_lvm.lvs.{{ lv_name }} is defined
          - ansible_lvm.lvs.{{ lv_name }}.vg == "{{ vg_name }}"
        fail_msg: "{{ vg_name }}/{{ lv_name }} does not exist!"
        success_msg: "{{ vg_name }}/{{ lv_name }} exists."

    - name: "is {{ vg_name }}/{{ lv_name }} already big enough?"
      assert:
        that:
          - ansible_lvm.lvs.{{ lv_name }}.size_g >= "{{ min_size_gb }}"
            # min_size_gb is in "{{ }}" because otherwise you get false
            # positives.
        success_msg: "{{ vg_name }}/{{ lv_name }} is already >= {{ min_size_gb }}GB"
        fail_msg: "{{ vg_name }}/{{ lv_name }} needs to be expanded"
      register: big_enough
      ignore_errors: yes

    - when: big_enough.failed
      block:
        - name: "how big is {{ vg_name }}/{{ lv_name }}?"
          set_fact:
            current_size_gb: "{{ ansible_lvm['lvs'][lv_name]['size_g']|float }}"
        - name: how much free space do we need?
          set_fact:
            needed_space_gb: "{{ min_size_gb|float - current_size_gb|float }}"
        - name: "how much free space does {{ vg_name }} have?"
          set_fact:
            free_space_gb: "{{ ansible_lvm['vgs'][vg_name]['free_g']|float }}"
        - name: "is there enough free space in {{ vg_name }}?"
          assert:
            that:
              - "{{ free_space_gb|float >= needed_space_gb|float }}"
          register: sufficient_free_space

    - when:
        - big_enough.failed == true
        - sufficient_free_space.failed == false # superfluous check, added for clarity
      block:
        - name: turn off swap
          command: swapoff '/dev/{{ vg_name }}/{{ lv_name }}'
        - name: expand the partition
          lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ min_size_gb }}G"
        - name: recreate swap
          command: mkswap '/dev/{{ vg_name }}/{{ lv_name }}'
        - name: turn on swap
          command: swapon '/dev/{{ vg_name }}/{{ lv_name }}'
