---
# file: playbook-expand-swap.yml

- name: expand swap partition
  hosts: all
  become: yes
  vars:
    vg_name: sysvg
    lv_name: swap
    min_size_gb: 4

  tasks:

    - name: "does {{ vg_name }}/{{ lv_name }} exist?"
      assert:
        that:
          - ansible_lvm.vgs.{{ vg_name }} is defined
          - ansible_lvm.lvs.{{ lv_name }} is defined
          - ansible_lvm.lvs.{{ lv_name }}.vg == "{{ vg_name }}"
        fail_msg: "{{ vg_name }}/{{ lv_name }} does not exist!"
        success_msg: "{{ vg_name }}/{{ lv_name }} exists."

    - name: "is {{ vg_name }}/{{ lv_name }} already big enough?"
      assert:
        that:
          - ansible_lvm.lvs.{{ lv_name }}.size_g >= "{{ min_size_gb }}"
        success_msg: "{{ vg_name }}/{{ lv_name }} is already >= {{ min_size_gb }}GB"
        fail_msg: "{{ vg_name }}/{{ lv_name }} needs to be expanded"
      register: size_check
      ignore_errors: yes

    - when: size_check.failed
      block:
        - name: turn off swap
          command: swapoff '/dev/{{ vg_name }}/{{ lv_name }}'
        - name: expand the partition
          lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ min_size_gb }}G"
        - name: recreate swap
          command: mkswap '/dev/{{ vg_name }}/{{ lv_name }}'
        - name: turn on swap
          command: swapon '/dev/{{ vg_name }}/{{ lv_name }}'
